#!/bin/bash
shopt -s extglob

function setArrayWithCmd()
{
    cmdArray=("$@")

    if [[ ! -z "$cmdArray" ]]
    then
        echo "the cmd is in the array espere touch >>>><   ${cmdArray[0]}"
	echo "the cmd is in the array espere mv >>>><  ${cmdArray[1]}"
    else
	echo "the array is emtpy"
    fi
} #useless $@ remplis le tableau command arg; command arg; ne coupe pas au premier espace!!

function processPool()
{
    tpmArray+=("$@")
    index=0

    echo "debut de function the command ${tpmArray[0]}"
    echo "debut de funtiion for the command ${tpmArray[1]}"    #function ProcessPool à mettre en dynamique

      #test pas finis
    for i in {${#tmpArray[@]}};
    do
	if [[ ! -z "$tmpArray[0]" ]]
	then
	    command ${tpmArray[0]} & #doit crée un nouveau process mais ont le meme PID sur les 2cmd
	    PID+=($!) # surment par ce que je ne les lancent pas en même temps
	    echo "The PID Value is ${PID} for the command ${tpmArray[0]}"
	else
	    echo "c'est la bite first argument"
	fi
	if [[ ! -z "$tmpArray[$i]" ]]
	then
	    command ${tpmArray[1]} &
	    PID+=($!)
	    echo "The PID Value is ${PID} for the command ${tpmArray[1]}"
	else
	    echo "c'est la bite second argument"
	fi
    done
}

processPool "touch test" "mv test test01"
#echo == return en C
