#!/bin/bash
shopt -s extglob

function processPool()
{
    tmpArray+=("$@")
    PID=()
    index=(0)

    echo "debut de function the first command ${tmpArray[0]}"
    echo "debut de funtiion the second command ${tmpArray[1]}"
    echo "debut de function the third command ${tmpArray[2]}"
    
    echo "the lenght of the array is ${#tmpArray[@]}"

    for cmd in {${#tmpArray[@]}};
    do
	if [[ ! -z "$tmpArray[@]" ]]
	then
	    command ${tmpArray[0]} &
	    PID+=($!)

	    echo "cmd === $cmd"

	    command ${tmpArray[1]} &
	    PID+=($!)

	    command ${tmpArray[2]} &
	    PID+=($!)
	    
	    echo "this is all the pid ${PID[@]}"
	else
	    echo "c'est le fail pas d'argument"
	fi
	for pids in "${PID[@]}"; do
	    printf "waiting for the %d..." "$pids"
	    wait $pid
	    echo 'done.'
	done
    done
}

processPool "touch test" "mv testok test12" "cat rootOrNot"
#echo == return en C
